name: JaCoCo Agent - Maven Tests

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: 'maven'

      - name: Validate Maven Wrapper
        run: mvn --version
        working-directory: /

      - name: Run Tests
        run: mvn clean test jacoco:report
        working-directory: /

      - name: Archive coverage data
        uses: actions/upload-artifact@v2
        with:
          name: maven-coverage-data-jacoco
          path: .qodana/code-coverage
          
      - name: My Debug
        run: |
          ls .qodana
          ls .qodana/code-coverage
          cat .qodana/code-coverage/jacoco.xml
    
      - name: Qodana Scan
        uses: JetBrains/qodana-action@v2023.3
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}
        with:        
          pr-mode: false
          upload-result: true
